#!/usr/bin/env python3
"""Import user inputs and generate the Ninja build."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tempfile

from tools import host
from tools.common import ROOT, read_json, validate_rom, validate_toolchain, write_bytes, write_json
from tools.inputs import InputError, import_compiler


def ninja_path(value: str) -> str:
    if "\n" in value or "\r" in value:
        raise InputError("Build paths cannot contain newlines.")
    return value.replace("$", "$$").replace(" ", "$ ").replace(":", "$:")


def command_line(parts: list[str]) -> str:
    command = subprocess.list2cmdline(parts) if os.name == "nt" else shlex.join(parts)
    return command.replace("$", "$$")


def generate(settings: dict, config: dict, suite: dict) -> None:
    version = settings["toolchain"]
    output = f"build/{version}"
    python = command_line([sys.executable])
    deps = ["configure.py", ".local/config.json", "config/build.json", "config/toolchains.json",
            *[p.as_posix() for p in Path("tools").glob("*.py")]]
    compiler_files = [f".local/toolchains/{version}/{name}" for name in suite["files"]]
    launcher_files = [settings["launcher"]["path"]] if settings["launcher"]["name"] == "wibo" else []
    headers = [p.as_posix() for p in sorted(Path("include").glob("*.h"))]
    common = " ".join(ninja_path(p) for p in deps + compiler_files + launcher_files)
    lines = [
        "# Generated by configure.py.",
        "ninja_required_version = 1.10",
        f"builddir = {output}",
        # Keep old compiler processes serial. Each also has private scratch files.
        "pool producer",
        "  depth = 1",
        "rule step",
        f"  command = {python} -m tools.build {version} $action",
        "  description = $label",
        "  pool = producer",
        "rule configure",
        f"  command = {python} configure.py --toolchain {version} --offline",
        "  description = CONFIGURE",
        "  generator = 1",
        "build build.ninja: configure configure.py config/build.json config/toolchains.json "
        "config/host-tools.json tools/host.py tools/common.py tools/inputs.py include tools",
        f"build {output}/rom_assets.h: step .local/retail.bin config/artwork.json | {common}",
        "  action = artwork",
        "  label = EXTRACT artwork",
        f"build {output}/runtime.lib {output}/runtime.json {output}/runtime.log: step | {common}",
        "  action = runtime",
        "  label = LBG runtime",
    ]
    objects, records = [], []
    for index, source in enumerate(config["sources"]):
        stem = f"{output}/{index:02d}"
        objects.append(f"{stem}.obj")
        records.append(f"{stem}.json")
        inputs = [f"src/{source['file']}", *headers]
        if source["file"] == "graphics.c":
            inputs.append(f"{output}/rom_assets.h")
        lines.extend([
            f"build {stem}.obj {stem}.json {stem}.log: step "
            + " ".join(ninja_path(p) for p in inputs) + f" | {common}",
            f"  action = compile {index}",
            f"  label = CH38 {source['file']}",
        ])
    lines.extend([
        f"build {output}/pw.bin {output}/pw.map {output}/link.sub "
        f"{output}/link.json {output}/link.log {output}/build.json: step "
        + " ".join(objects + records + [f"{output}/runtime.lib", f"{output}/runtime.json"])
        + f" | {common}",
        "  action = link",
        "  label = LINK pw.bin",
        # A phony input reruns the inexpensive literal comparison on every build.
        "build always: phony",
        f"build {output}/verified.json: step {output}/pw.bin .local/retail.bin always | {common}",
        "  action = verify",
        "  label = VERIFY retail ROM",
        f"build firmware: phony {output}/pw.bin",
        f"build verify: phony {output}/verified.json",
        "default verify",
        "",
    ])
    write_bytes(ROOT / "build.ninja", "\n".join(lines).encode("utf-8"))


def configure(args) -> None:
    for name in ("rom", "compiler", "work_dir"):
        value = getattr(args, name)
        if value is not None:
            setattr(args, name, value.expanduser().resolve())
    if args.wibo and Path(args.wibo).expanduser().is_file():
        args.wibo = str(Path(args.wibo).expanduser().resolve())
    os.chdir(ROOT)
    config = read_json(ROOT / "config/build.json")
    inventories = read_json(ROOT / "config/toolchains.json")
    local = ROOT / ".local"
    settings_file = local / "config.json"
    previous = read_json(settings_file) if settings_file.is_file() else {}
    rom_path = args.rom or local / "retail.bin"
    if not rom_path.is_file():
        raise InputError("Supply --rom PATH and --compiler PATH on first configuration.")
    rom = validate_rom(rom_path, config["target"])
    local.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="configure-", dir=local) as temporary:
        stage = Path(temporary)
        candidates = {args.toolchain: inventories[args.toolchain]} if args.toolchain else inventories
        imported = import_compiler(args.compiler, candidates, stage) if args.compiler else None
        if imported and args.toolchain and imported != args.toolchain:
            raise InputError(f"Input contains {imported}, but --toolchain requests {args.toolchain}.")
        version = args.toolchain or imported or previous.get("toolchain")
        if version not in inventories:
            raise InputError("Supply --compiler PATH for a qualified 6.02.01 or 6.02.02 suite.")
        suite = stage / version if imported else local / "toolchains" / version
        validate_toolchain(suite, inventories[version]["files"])
        override = args.wibo or os.environ.get("PW_WIBO") or previous.get("wibo")
        if args.managed_wibo:
            override = None
        launcher = host.select(override, args.offline)
        scratch = args.work_dir or previous.get("work_dir") or (
            "/tmp" if sys.platform == "darwin" else tempfile.gettempdir())
        scratch = Path(scratch).expanduser().resolve()
        if not str(scratch).isascii() or not scratch.is_dir():
            raise InputError("Supply --work-dir PATH to an existing, writable ASCII directory.")
        with tempfile.TemporaryDirectory(prefix="pw-check-", dir=scratch):
            pass
        if imported:
            destination = local / "toolchains" / version
            destination.parent.mkdir(exist_ok=True)
            backup = stage / "previous"
            if destination.exists():
                destination.replace(backup)
            try:
                suite.replace(destination)
            except OSError:
                if backup.exists():
                    backup.replace(destination)
                raise
        if args.rom:
            write_bytes(local / "retail.bin", rom)
        settings = {"toolchain": version, "launcher": launcher, "work_dir": str(scratch)}
        if override:
            settings["wibo"] = launcher["path"]
        write_json(settings_file, settings)
        generate(settings, config, inventories[version])
    print(f"Configured {version}. Run ninja to build and verify all 49,152 bytes.")
    if shutil.which("ninja") is None:
        print("Ninja is not on PATH yet; see docs/build.md for installation.")
    if not host.qualified_host():
        print("This host combination is unverified; see docs/build.md for tested combinations.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, help="user-provided retail firmware image")
    parser.add_argument("--compiler", type=Path, help="qualified suite directory, updater EXE or ZIP")
    parser.add_argument("--toolchain", choices=["6.02.01", "6.02.02"])
    parser.add_argument("--wibo", help="use an existing Wibo executable instead of the managed download")
    parser.add_argument("--managed-wibo", action="store_true", help="return to the managed Wibo default")
    parser.add_argument("--offline", action="store_true", help="never download a missing host tool")
    parser.add_argument("--work-dir", type=Path, help="ASCII directory for private compiler scratch files")
    args = parser.parse_args()
    if args.wibo and args.managed_wibo:
        parser.error("--wibo and --managed-wibo are mutually exclusive")
    try:
        configure(args)
    except (InputError, OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
