import {useEffect,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,Play,Pause,StepForward,RotateCcw,Upload,Download,Bookmark,GitFork,Volume2,VolumeX,Maximize2,RotateCcwSquare,Check,FileCode2} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs'
import {TooltipProvider} from '@/components/ui/tooltip'
import {Slider} from '@/components/ui/slider'
import {Switch} from '@/components/ui/switch'
import {Badge} from '@/components/ui/badge'
import {Input} from '@/components/ui/input'
import {Info,Choice,Control,LCD,Plot,Section,Metric,viewName,time} from '@/components/lab'
import {createFirmwareAudio} from './audio.js'
import {mountModel} from './model.js'
import './App.css'
import {defaults as initialPhysics,surfaces} from '../../physics-defaults.js'
const defaultScene={environment:'outdoor',zoom:1.35,response:65,vectors:false,follow:true,elevation:12,azimuth:0,sunElevation:50,sunAzimuth:-25,sunIntensity:3}
const fixtures=[['furret-eeprom-64KiB.bin','Furret EEPROM'],['64k-full-rom.bin','64k full ROM'],['current-save-64KiB.bin','Current save'],['eeprom-editor-sample.bin','Editor sample'],['pp-attachment-53676.bin','Attachment 53676'],['pp-attachment-54370.bin','Attachment 54370'],['pp-attachment-55107.bin','Attachment 55107'],['project-pokemon-pweep-64KiB.bin','Project Pokémon'],['blank','Blank EEPROM']]
const n=(value:number=0)=>value.toLocaleString('en-US')
function download(bytes:any,name:string,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export default function App(){
 const [exportFile,setExportFile]=useState<{url:string,name:string}|null>(null)
 const [frame,setFrame]=useState<any>(null),[physics,setPhysics]=useState(initialPhysics),[sceneSettings,setSceneSettings]=useState(defaultScene),[metrics,setMetrics]=useState({fps:0,maxFrame:0}),[tab,setTab]=useState('environment'),[fixture,setFixture]=useState(fixtures[0][0]),[notice,setNotice]=useState('Loading firmware…'),[fault,setFault]=useState(''),[history,setHistory]=useState<any>({items:[],selected:null}),[checkpoints,setCheckpoints]=useState<any[]>([]),[branches,setBranches]=useState<any>(null),[branchIndex,setBranchIndex]=useState(11),[forking,setForking]=useState(false),[functions,setFunctions]=useState<any[]>([]),[build,setBuild]=useState<any>(null),[proof,setProof]=useState<any>(null),[verification,setVerification]=useState<any>(null),[selectedFn,setSelectedFn]=useState<any>(null),[code,setCode]=useState(''),[filter,setFilter]=useState(''),[audioEnabled,setAudioEnabled]=useState(false),[inset,setInset]=useState(true)
 const host=useRef<HTMLDivElement>(null),model=useRef<any>(null),worker=useRef<Worker|null>(null),futures=useRef<Worker|null>(null),file=useRef<HTMLInputElement>(null),keys=useRef(0),current=useRef<any>(null),manualPause=useRef(false),audio=useRef<any>(null)
 const send=(type:string,extra:object={})=>worker.current?.postMessage({type,...extra})
 const changePhysics=(value:Partial<typeof initialPhysics>)=>{setPhysics(p=>({...p,...value}));send('physics',{value})}
 const changeScene=(value:Partial<typeof sceneSettings>)=>{setSceneSettings(s=>({...s,...value}));model.current?.configure(value)}
 const keyChange=(value:number)=>{keys.current=value;send('buttons',{value})}
 useEffect(()=>{
  let alive=true,lastUI=0
  const w=new Worker('/runtime-worker.js',{type:'module'}),fw=new Worker('/futures-worker.js',{type:'module'});worker.current=w;futures.current=fw
  try{model.current=mountModel(host.current,(drag: any)=>send('physics',{value:{drag}}),keyChange,(m: {fps:number,maxFrame:number})=>alive&&setMetrics(m),(value:Partial<typeof defaultScene>)=>alive&&setSceneSettings(s=>({...s,...value})))}catch(err){setFault('3D view failed: '+String(err))}
  w.onmessage=({data:d})=>{if(!alive)return
   if(d.type==='pose'){model.current?.updatePose(d.pose,d.paused);return}
   if(d.type==='frame'){current.current=d;model.current?.updateScreen(d.pixels);if(performance.now()-lastUI>=120||d.paused){setFrame(d);lastUI=performance.now()}return}
   if(d.type==='audio'){audio.current?.packet(d);return}
   if(d.type==='audio-reset'){audio.current?.reset();return}
   if(d.type==='settings')setPhysics({...initialPhysics,...d.physics})
   if(d.type==='history')setHistory(d)
   if(d.type==='loaded'){setPhysics({...initialPhysics,...d.physics});setNotice(d.label+' loaded.');setFault('');manualPause.current=false;setBranches(null);model.current?.configure({environment:'outdoor'});setSceneSettings(s=>({...s,environment:'outdoor'}))}
   if(d.type==='restored'){setPhysics({...initialPhysics,...d.physics});const environment=d.physics.environment||'outdoor';setSceneSettings(s=>({...s,environment}));model.current?.configure({environment});manualPause.current=true}
   if(d.type==='save'||d.type==='raw'){const data=new Uint8Array(d.bytes);let binary='';for(let i=0;i<data.length;i+=8192)binary+=String.fromCharCode(...data.subarray(i,i+8192));const url='data:application/octet-stream;base64,'+btoa(binary);setExportFile(old=>{if(old)URL.revokeObjectURL(old.url);return {url,name:'pokewalker-eeprom.bin'}});setNotice('EEPROM ready: 65,536 bytes.')}
   if(d.type==='checkpoint'){setCheckpoints(all=>[d,...all].slice(0,8));setNotice('State saved in this session.')}
   if(d.type==='snapshot')fw.postMessage(d,[d.memory])
   if(d.type==='error'){setFault(d.message);manualPause.current=true;setForking(false)}
  }
  fw.onmessage=({data:d})=>{if(!alive)return;setForking(false);if(d.type==='error'){setFault(d.message);return}setBranches(d);setBranchIndex(11);setNotice('Six branches completed.')}
  w.postMessage({type:'init'})
  w.onerror=event=>{setFault(event.message||'Runtime worker stopped.');setForking(false)}
  Promise.all(['functions','build','baseline','verification'].map(name=>fetch('/generated/'+name+'.json').then(r=>r.json()))).then(([f,b,p,v])=>{if(!alive)return;setFunctions(f);setBuild(b);setProof(p);setVerification(v);setSelectedFn(f.find((x:any)=>x.name==='MainTick'))}).catch(err=>setNotice('Build metadata could not load: '+String(err)))
  const map:Record<string,number>={ArrowLeft:4,ArrowRight:8,Enter:2,' ':2}
  const down=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(['INPUT','TEXTAREA','SELECT','BUTTON'].includes(target.tagName)||target.closest('[role="slider"],[role="combobox"],[role="tablist"]'))return;if(map[e.key]){e.preventDefault();keyChange(keys.current|map[e.key])}}
  const up=(e:KeyboardEvent)=>{if(map[e.key])keyChange(keys.current&~map[e.key])}
  const blur=()=>keyChange(0),visibility=()=>send('pause',{value:document.hidden||manualPause.current})
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility)
  return()=>{alive=false;w.terminate();fw.terminate();model.current?.dispose();model.current=null;window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);audio.current?.close()}
 },[])
 useEffect(()=>{if(!selectedFn)return;let alive=true;fetch('/source/'+selectedFn.file).then(r=>r.text()).then(t=>{if(alive)setCode(t)});return()=>{alive=false}},[selectedFn?.file])
 const s=frame?.stats||Array(34).fill(0),paused=frame?.paused||false
 const selectedHistoryIndex=history.selected===null?history.items.length-1:history.items.findIndex((h:any)=>h.id===history.selected)
 const loadFixture=async(value:string)=>{setFixture(value);setFault('');if(value==='blank'){send('blank');return}try{const response=await fetch('/fixtures/'+value);if(!response.ok)throw Error('EEPROM file not found.');send('load',{bytes:await response.arrayBuffer(),label:fixtures.find(f=>f[0]===value)?.[1]||value})}catch(e){setFault(String(e))}}
 const toggleAudio=async()=>{if(audio.current){await audio.current.close();audio.current=null;setAudioEnabled(false);return}audio.current=await createFirmwareAudio();setAudioEnabled(true)}
 const holdProps=(mask:number)=>({onPointerDown:(e:any)=>{e.currentTarget.setPointerCapture(e.pointerId);keyChange(keys.current|mask)},onPointerUp:()=>keyChange(keys.current&~mask),onPointerCancel:()=>keyChange(keys.current&~mask),onKeyDown:(e:any)=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();keyChange(mask)}},onKeyUp:(e:any)=>{if(e.key===' '||e.key==='Enter')keyChange(0)}})
 const filteredFunctions=functions.filter(f=>f.name.toLowerCase().includes(filter.toLowerCase()))
 const activeFunctions=functions.filter(f=>frame?.delta[f.id]).sort((a,b)=>(frame.delta[b.id]||0)-(frame.delta[a.id]||0)).slice(0,7)
 const sourceStart=Math.max(0,(selectedFn?.line||1)-3),sourceEnd=functions.filter(f=>f.file===selectedFn?.file&&f.line>selectedFn.line).sort((a,b)=>a.line-b.line)[0]?.line-1||code.split('\n').length
 return <TooltipProvider delayDuration={250}><div className="app-shell">
  <header className="app-header"><div className="app-title"><span className="device-symbol"/><h1>Pokéwalker</h1><Badge variant="secondary">Browser port</Badge></div><div className="file-toolbar"><div className="fixture-select"><Choice label="EEPROM image" value={fixture} options={fixture==='imported'?[['imported',frame?.label||'Imported EEPROM'],...fixtures]:fixtures} onChange={loadFixture}/></div><Button variant="outline" size="sm" onClick={()=>file.current?.click()}><Upload/>Import</Button><Button variant="outline" size="sm" disabled={!frame} onClick={()=>send('save')}><Download/>Export</Button><Info label="EEPROM">Import a 64 KiB EEPROM file. Export commits the live save to both EEPROM mirrors. Files stay in this browser session.</Info><input ref={file} type="file" accept=".bin,.eep,.eeprom" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size!==65536){setFault('Select a 65,536-byte EEPROM file.');e.target.value='';return}setFixture('imported');send('load',{bytes:await f.arrayBuffer(),label:f.name});e.target.value=''}}/></div></header>
  {exportFile&&<div className="export-ready"><span>{exportFile.name} · 64 KiB</span><Button variant="outline" size="sm" asChild><a href={exportFile.url} download={exportFile.name}><Download/>Save EEPROM</a></Button><Button variant="ghost" size="sm" onClick={()=>{URL.revokeObjectURL(exportFile.url);setExportFile(null)}}>Close</Button></div>}
  {fault&&<div className="error-banner" role="alert">{fault}<Button variant="outline" size="sm" onClick={()=>{setFault('');send('reset')}}>Reload EEPROM</Button></div>}
  <main className="workspace">
   <div className="device-panel">
    <div className="device-panel-top"><div><span className={'state-dot '+(paused?'paused':'')}/>{paused?'Paused':'Running'}<span className="muted">{s[26]?'LCD asleep':viewName(s[5])}</span></div><div className="small-actions"><Button variant="ghost" size="icon-sm" aria-label="Reset device position" onClick={()=>send('recenter')}><RotateCcwSquare/></Button><Button variant="ghost" size="icon-sm" aria-label="Toggle LCD inset" onClick={()=>setInset(v=>!v)}><Maximize2/></Button><Button variant="ghost" size="icon-sm" aria-label={audioEnabled?'Mute audio':'Enable audio'} onClick={toggleAudio}>{audioEnabled?<Volume2/>:<VolumeX/>}</Button></div></div>
    <div className="scene-wrap"><div ref={host} className="scene"/>{inset&&<div className="lcd-inset"><LCD pixels={frame?.pixels}/><span>LCD · 96 × 64</span></div>}<div className="scene-caption">Drag to move. Right-drag to orbit.<Info label="Scene controls">Select Free motion to lift and release the device. Select Pendulum to use the string. Use the wheel to zoom. Moving outside the scene releases the grip. Firm hold keeps the pickup orientation; point grip lets the shell rotate about the selected point. Use the three buttons below to operate the firmware.</Info></div><div className="scale-readout">Ø {Math.round(physics.diameter*1000)} mm</div></div>
    <div className="device-controls"><div className="hardware-buttons"><Button variant="outline" aria-label="Left device button" {...holdProps(4)}><ArrowLeft/></Button><Button variant="outline" aria-label="Center device button" {...holdProps(2)}><span className="center-key"/></Button><Button variant="outline" aria-label="Right device button" {...holdProps(8)}><ArrowRight/></Button><Info label="Device buttons">Use Left, Enter, and Right on the keyboard. Hold the center button to wake the device. Buttons use the firmware debounce logic.</Info></div><div className="device-values"><Metric label="Steps today" value={n(s[7])}/><Metric label="Watts" value={n(s[6])}/><Metric label="Device time" value={new Date(s[19]*1000).toISOString().slice(11,19)}/></div></div>
    <div className="transport"><Button size="sm" disabled={!frame} onClick={()=>{manualPause.current=!paused;send('pause',{value:!paused})}}>{paused?<Play/>:<Pause/>}{paused?'Resume':'Pause'}</Button><Button variant="outline" size="icon-sm" aria-label="Advance one firmware tick" onClick={()=>{manualPause.current=true;send('step')}}><StepForward/></Button><div className="speed-select"><Choice label="Playback speed" value={String(frame?.speed||1)} options={[.125,.25,.5,1,2,4,8,16].map(v=>[String(v),v+'×'])} onChange={value=>send('speed',{value:Number(value)})}/></div><Info label="Playback speed">1× preserves the original device intervals: 16 Hz foreground work, 4 Hz LCD requests, and a 1 Hz clock. Step advances 62.5 ms. Playback speed scales device time, audio tempo, and audio pitch.</Info><time data-testid="virtual-time">{time(s[0])}</time><Button variant="ghost" size="icon-sm" aria-label="Save state" onClick={()=>send('checkpoint')}><Bookmark/></Button><Button variant="ghost" size="icon-sm" aria-label="Reset firmware" onClick={()=>{manualPause.current=false;send('reset')}}><RotateCcw/></Button></div>
    <div className="timeline"><div className="timeline-top"><span>Rewind<Info label="Rewind">The last 32 states are kept at one-second intervals. Select a time to restore memory and motion. Resume to start a new branch from that time.</Info></span><span>{history.selected===null?'Live':`Restored ${time(s[0])}`}</span></div><Slider aria-label="Rewind timeline" disabled={history.items.length<2} min={0} max={Math.max(1,history.items.length-1)} step={1} value={[Math.max(0,selectedHistoryIndex)]} onValueChange={v=>{const h=history.items[v[0]];if(h){manualPause.current=true;send('rewind',{id:h.id})}}}/><div className="timeline-times"><span>{time(history.items[0]?.time||0)}</span><span>{time(history.items.at(-1)?.time||0)}</span></div></div>
   </div>
   <aside className="inspector"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="inspector-tabs"><TabsTrigger value="environment">Scene</TabsTrigger><TabsTrigger value="motion">Motion</TabsTrigger><TabsTrigger value="memory">Memory</TabsTrigger><TabsTrigger value="source">Source</TabsTrigger><TabsTrigger value="history">History</TabsTrigger><TabsTrigger value="build">Build</TabsTrigger></TabsList>
    <div className="inspector-body">
    <TabsContent value="environment"><div className="settings-reset"><Button variant="outline" size="sm" onClick={()=>{send('defaults');send('speed',{value:1});changeScene(defaultScene);setNotice('Scene and playback settings reset.')}}><RotateCcw/>Reset settings</Button></div><Section title="Environment"><div className="two-cols"><label>Setting<Choice label="Environment setting" value={sceneSettings.environment} options={[["outdoor","Grass"],["desk","Desk"],["studio","Studio"]]} onChange={value=>{changeScene({environment:value});changePhysics({environment:value,...surfaces[value as keyof typeof surfaces]})}}/></label><label>Constraint<Choice label="Motion constraint" value={physics.tether} options={[["pendulum","Pendulum"],["free","Free motion"],["fixed","Fixed"]]} onChange={tether=>{changePhysics({tether,lockFacing:tether==='fixed'});send('recenter')}}/></label></div><div className="preset-row"><Button variant="outline" size="sm" onClick={()=>{changePhysics({tether:'pendulum',mode:'still',wind:6,direction:-30,mass:initialPhysics.mass,clip:true,length:initialPhysics.length,lockFacing:false});send('recenter')}}>Pendulum + fan</Button><Button variant="outline" size="sm" onClick={()=>{changePhysics({tether:'free',mode:'still',wind:0,lockFacing:false});send('recenter')}}>Drop test</Button><Button variant="outline" size="sm" onClick={()=>{changePhysics({tether:'fixed',mode:'walk',wind:0,lockFacing:true});send('recenter')}}>Walking</Button></div><div className="preset-row"><Button variant="outline" size="sm" onClick={()=>send('recenter',{action:'upright'})}>Turn upright</Button><Button variant="outline" size="sm" onClick={()=>{changePhysics({tether:'free',lockFacing:false});send('recenter',{action:'flip'});changeScene({elevation:50})}}>Screen up</Button></div></Section>
     <Section title="Motion input" info="The scene generates signed accelerometer samples. The native firmware applies its original FFT and step logic. The force model is adjustable and is not a calibrated device model."><label className="switch-row top-switch">Keep screen forward<Switch aria-label="Keep screen forward" checked={physics.lockFacing} onCheckedChange={lockFacing=>changePhysics({lockFacing})}/></label><div className="two-cols"><label>Drive<Choice label="Motion drive" value={physics.mode==='walk'?'walk':'still'} options={[["still","Manual / wind"],["walk","Walking"]]} onChange={mode=>changePhysics({mode})}/></label><Control label="Cadence" value={physics.cadence} min={.5} max={4} step={.1} unit="Hz" onChange={cadence=>changePhysics({cadence})}/></div>{physics.tether==='pendulum'&&<Control label="Tether length" value={physics.length*100} min={5} max={25} step={.5} unit="cm" onChange={value=>changePhysics({length:value/100})}/>}<div className="two-cols"><Control label="Mass" value={physics.mass*1000} min={5} max={100} step={.1} unit="g" info="Nintendo specifies 20.6 g including the CR2032 battery, or 21.9 g with the belt clip." onChange={value=>changePhysics({mass:value/1000})}/><Control label="Damping" value={physics.damping} min={0} max={10} step={.05} unit="s⁻¹" onChange={damping=>changePhysics({damping})}/></div><label className="switch-row">Belt clip<Switch aria-label="Belt clip" checked={physics.clip} onCheckedChange={clip=>changePhysics({clip,mass:clip?.0219:.0206})}/></label><div className="two-cols physics-extra"><Control label="Gravity" value={physics.gravity} min={0} max={20} step={.1} unit="m/s²" onChange={gravity=>changePhysics({gravity})}/><Control label="Friction" value={physics.friction} min={0} max={1} step={.05} onChange={friction=>changePhysics({friction})}/></div><Control label="Restitution" value={physics.restitution} min={0} max={.8} step={.02} info="Contact rebound factor. Zero removes normal rebound; friction and rotation can still move the device." onChange={restitution=>changePhysics({restitution})}/><label>Mouse grip<Choice label="Mouse grip" value={physics.grip} options={[["firm","Firm hold"],["point","Point grip"]]} onChange={grip=>changePhysics({grip})}/></label><Control label="Grip response" value={physics.response} min={.2} max={4} step={.1} unit="×" info="Higher values make the hand target respond faster. Firm hold maintains the pickup orientation. Point grip permits rotation about the point you select." onChange={response=>changePhysics({response})}/></Section>
     {physics.tether==='pendulum'&&<Section title="String" info="The string carries tension and can go slack. Twist is stored as elastic energy and applies torque about the attachment axis. This is a torsional cord model; it does not simulate knots or self-contact."><div className="section-actions"><Button variant="outline" size="sm" onClick={()=>{changePhysics({lockFacing:false});send('recenter',{action:'twist'})}}>Twist one turn</Button><span className="note">{((frame?.pose?.twist||0)/(2*Math.PI)).toFixed(2)} turns</span></div><Control label="Twine diameter" value={physics.cordDiameter*1000} min={.5} max={2} step={.1} unit="mm" onChange={v=>changePhysics({cordDiameter:v/1000})}/><Control label="Torsional stiffness" value={physics.twistStiffness} min={0} max={20} step={.5} unit="µN·m/rad" info="Reference stiffness for 10 cm of 1 mm twine. Length and diameter scale the applied torque. This is an adjustable material estimate." onChange={twistStiffness=>changePhysics({twistStiffness})}/></Section>}
     <Section title="Fan" info="Air drag uses relative velocity, projected body area, and forces at four surface regions. Air density is 1.225 kg/m³. Drag, contact, and inertia are engineering approximations."><Control label="Air speed" value={physics.wind} min={0} max={24} step={.5} unit="m/s" onChange={wind=>changePhysics({wind})}/><div className="two-cols"><Control label="Direction" value={physics.direction} min={-180} max={180} step={5} unit="°" onChange={direction=>changePhysics({direction})}/><Control label="Gust strength" value={physics.gust*100} min={0} max={100} step={5} unit="%" onChange={value=>changePhysics({gust:value/100})}/></div><label className="switch-row">Oscillate<Switch aria-label="Oscillate fan" checked={physics.oscillate} onCheckedChange={oscillate=>changePhysics({oscillate})}/></label>{physics.oscillate&&<div className="two-cols"><Control label="Sweep angle" value={physics.sweep} min={5} max={90} step={5} unit="±°" onChange={sweep=>changePhysics({sweep})}/><Control label="Oscillation rate" value={physics.oscillationHz} min={.05} max={1} step={.05} unit="Hz" onChange={oscillationHz=>changePhysics({oscillationHz})}/></div>}<Control label="Fan height" value={physics.fanHeight*100} min={-8} max={8} step={.5} unit="cm" onChange={v=>changePhysics({fanHeight:v/100})}/><Button variant="ghost" size="sm" className="reset-subset" onClick={()=>changePhysics({wind:initialPhysics.wind,direction:initialPhysics.direction,gust:initialPhysics.gust,fanHeight:initialPhysics.fanHeight,oscillate:initialPhysics.oscillate,sweep:initialPhysics.sweep,oscillationHz:initialPhysics.oscillationHz})}>Reset fan</Button></Section>
     <Section title="View"><div className="two-cols"><Control label="Camera zoom" value={sceneSettings.zoom} min={.6} max={2.5} step={.05} unit="×" onChange={zoom=>changeScene({zoom})}/><Control label="Body diameter" value={physics.diameter*1000} min={24} max={80} step={1} unit="mm" info="The default diameter is 48 mm. This control changes physical area and model scale. Camera zoom changes only the view." onChange={value=>changePhysics({diameter:value/1000})}/></div><div className="two-cols physics-extra"><Control label="Camera elevation" value={sceneSettings.elevation} min={0} max={80} step={5} unit="°" onChange={elevation=>changeScene({elevation})}/><Control label="Camera azimuth" value={sceneSettings.azimuth} min={-180} max={180} step={5} unit="°" onChange={azimuth=>changeScene({azimuth})}/></div><Control label="LCD response" value={sceneSettings.response} min={0} max={150} step={5} unit="ms" info="Pixel settling time in the 3D view. This does not add firmware frames. The LCD inset always shows the current output without this effect." onChange={response=>changeScene({response})}/><label className="switch-row">Follow free motion<Switch aria-label="Follow free motion" checked={sceneSettings.follow} onCheckedChange={follow=>changeScene({follow})}/></label><label className="switch-row">Sensor axes<Switch aria-label="Show sensor axes" checked={sceneSettings.vectors} onCheckedChange={vectors=>changeScene({vectors})}/></label><Button variant="ghost" size="sm" className="reset-subset" onClick={()=>changeScene(defaultScene)}>Reset view</Button></Section><Section title="Sunlight"><div className="two-cols"><Control label="Sun elevation" value={sceneSettings.sunElevation} min={5} max={85} step={5} unit="°" onChange={sunElevation=>changeScene({sunElevation})}/><Control label="Sun azimuth" value={sceneSettings.sunAzimuth} min={-180} max={180} step={5} unit="°" onChange={sunAzimuth=>changeScene({sunAzimuth})}/></div><Control label="Light intensity" value={sceneSettings.sunIntensity} min={0} max={6} step={.1} unit="×" onChange={sunIntensity=>changeScene({sunIntensity})}/><Button variant="ghost" size="sm" className="reset-subset" onClick={()=>changeScene({sunElevation:50,sunAzimuth:-25,sunIntensity:3})}>Reset light</Button></Section>
    </TabsContent>
    <TabsContent value="motion"><Section title="Accelerometer" info="64 samples per axis. The firmware reads signed BMA150-style samples at 16 Hz. One count represents approximately 1/32 g."><div className="metrics-row">{['X','Y','Z'].map((axis,i)=><Metric key={axis} label={axis+' axis'} value={frame?.accel[i]||0}/>)}</div><Plot kind="wave" data={frame?.samples} index={s[12]}/><div className="plot-labels"><span>−4 s</span><span className="axis-key">X · Y · Z</span><span>Now</span></div></Section><div className="signal-flow"><span>XYZ samples</span><ArrowRight/><span>FFT</span><ArrowRight/><span>Cadence</span><ArrowRight/><span>Steps</span></div><Section title="Frequency spectrum" info="These bins come from MotionProcess in the compiled C code. The shaded range contains the cadence bins used by the firmware."><Plot kind="spectrum" data={frame?.spectrum}/><div className="plot-labels"><span>0 Hz</span><span>1.25–3.5 Hz cadence range</span><span>7.75 Hz</span></div><div className="metrics-row"><Metric label="Window" value={`${s[12]} / 64`}/><Metric label="Cadence" value={s[4]?(s[14]?(s[14]/2048).toFixed(2)+' Hz':'Rejected'):'Waiting'}/><Metric label="Epochs" value={n(s[4])}/></div></Section><Section title="Step accumulator" info="The firmware carries fractional steps in Q9 form: 512 units equal one step. It converts accepted steps into Watts."><div className="metrics-row"><Metric label="Fraction" value={`${s[20]} / 512`}/><Metric label="Latest batch" value={s[21]}/><Metric label="Next Watt" value={`${s[24]} / 20`}/></div><div className="progress-track"><span style={{width:s[20]/512*100+'%'}}/></div></Section><Section title="Rigid body"><div className="metrics-row"><Metric label="Contacts" value={frame?.physical?.contacts||0}/><Metric label="Kinetic energy" value={((frame?.physical?.kinetic||0)*1000).toFixed(2)+' mJ'}/><Metric label="String tension" value={((frame?.physical?.tension||0)*1000).toFixed(1)+' mN'}/></div><div className="metrics-row">{['X','Y','Z'].map((axis,i)=><Metric key={axis} label={axis+' rotation'} value={(frame?.physical?.av?.[i]||0).toFixed(2)+' rad/s'}/>)}</div></Section><Section title="Execution"><div className="metrics-row"><Metric label="Foreground" value={['MainTick','BeepTick','IR wait'][s[27]]}/><Metric label="C time / tick" value={(frame?.compute||0).toFixed(3)+' ms'}/><Metric label="Scene" value={metrics.fps+' fps'}/></div><p className="note">The LCD requests an update at 4 Hz. Scene motion is sent at 60 Hz.</p></Section></TabsContent>
    <TabsContent value="memory"><Section title="Workspace" info="These 1,802 bytes are read directly from native Wasm memory. Motion and audio reuse part of this storage."><div className="memory-layout"><span>Samples / audio · 266 B</span><span>Scratch · 1,536 B</span></div><Plot kind="memory" data={frame?.work}/><div className="metrics-row"><Metric label="Active user" value={s[27]===1?'Audio':'Motion'}/><Metric label="Scratch used" value={s[13]+' B'}/><Metric label="High water" value={s[32]+' B'}/></div></Section><Section title="EEPROM access" info="Each cell contains 128 EEPROM bytes. Green records reads. Brown records writes. Move the pointer over a cell to see its address and access counts."><Plot kind="eeprom" data={frame?.heat} other={frame?.writeHeat}/><div className="plot-labels"><span>0x0000</span><span>64 KiB</span><span>0xFFFF</span></div><div className="metrics-row"><Metric label="Read calls" value={n(s[15])}/><Metric label="Write calls" value={n(s[16])}/><Metric label="Save mirrors" value="2"/></div></Section><Section title="Live state"><div className="state-table"><Metric label="PRNG state" value={'0x'+s[17].toString(16).padStart(8,'0')}/><Metric label="System flags" value={'0x'+s[10].toString(16).padStart(4,'0')}/><Metric label="Event flags" value={'0x'+s[11].toString(16).padStart(4,'0')}/><Metric label="Total steps" value={n(s[8])}/></div><Button variant="outline" size="sm" onClick={()=>send('raw')}><Download/>Export stored EEPROM</Button><Info label="Stored EEPROM">Export the current EEPROM bytes without first committing the live save.</Info></Section></TabsContent>
    <TabsContent value="source"><Section title="Active functions" info="Entry counters are inserted into the C source before compilation. Select a function to inspect its source. Counts include compiler-inlined calls."><div className="function-list">{activeFunctions.length?activeFunctions.map(f=><button key={f.id} onClick={()=>setSelectedFn(f)} className={selectedFn?.id===f.id?'selected':''}><FileCode2 size={14}/><span>{f.name}</span><small>+{n(frame.delta[f.id])}</small></button>):<p className="note">No calls in this interval.</p>}</div></Section><Section title="Source"><Input aria-label="Find a C function" placeholder="Find a function" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="source-choice"><Choice label="C function" value={String(selectedFn?.id??'')} options={filteredFunctions.map(f=>[String(f.id),f.name])} onChange={id=>setSelectedFn(functions.find(f=>f.id===Number(id)))}/></div><div className="code-caption"><span>{selectedFn?.file}:{selectedFn?.line}</span><span>{n(frame?.counts[selectedFn?.id]||0)} calls</span></div><pre className="source-code">{code.split('\n').slice(sourceStart,sourceEnd).map((line,i)=><div key={i} className={sourceStart+i+1===selectedFn?.line?'declaration':''}><span>{sourceStart+i+1}</span>{line}</div>)}</pre></Section></TabsContent>
    <TabsContent value="history"><Section title="Saved states" info="Each state contains complete native memory and physical input state. Restore pauses the device. These states exist only in this tab."><div className="section-actions"><Button variant="outline" size="sm" onClick={()=>send('checkpoint')}><Bookmark/>Save state</Button><span className="note">{checkpoints.length} / 8</span></div>{checkpoints.length?<div className="checkpoint-grid">{checkpoints.map((c,i)=><button key={i} onClick={()=>{manualPause.current=true;send('restore',{state:c.state});setNotice('State restored and paused.')}}><LCD pixels={c.pixels}/><span>{time(c.stats[0])}</span><small>{viewName(c.stats[5])} · {c.stats[7]} steps</small></button>)}</div>:<p className="empty-note">No saved states.</p>}</Section><Section title="Branches" info="Six independent WebAssembly instances start from the same complete memory state. Each runs 12 device seconds with a different input. The live instance continues separately."><div className="section-actions"><Button variant="outline" size="sm" disabled={!frame||forking} onClick={()=>{setForking(true);send('snapshot')}}><GitFork/>{forking?'Running…':'Run six branches'}</Button><span className="note">12 s each</span></div>{branches?<><div className="branch-summary">Completed in {branches.elapsed.toFixed(1)} ms · {time(branches.startedAt||0)} start</div><div className="branch-grid">{branches.branches.map((b:any)=><div className="branch" key={b.name}><span>{b.name}</span><LCD pixels={b.frames[branchIndex]}/><div>+{b.steps[branchIndex]} steps</div><small>{b.states.map(viewName).join(' → ')}</small></div>)}</div><div className="control-top"><span>Branch time</span><span>+{branchIndex+1} s</span></div><Slider aria-label="Branch time" value={[branchIndex]} min={0} max={11} step={1} onValueChange={v=>setBranchIndex(v[0])}/></>:<p className="empty-note">Run branches to compare button input, walking, and stillness.</p>}</Section></TabsContent>
    <TabsContent value="build"><Section title="Native build"><div className="state-table"><Metric label="Compiler" value="LLVM Clang 23"/><Metric label="Target" value="wasm32-unknown-unknown"/><Metric label="C translation units" value={build?.sources?.length||'—'}/><Metric label="Instrumented functions" value={functions.length}/><Metric label="Wasm size" value={build?(build.wasmBytes/1024).toFixed(1)+' KiB':'—'}/><Metric label="JavaScript imports" value={frame?.imports?.length??'—'}/></div><p className="note">The application C source is compiled to WebAssembly. Browser backends supply the LCD, EEPROM, input, and timer boundaries. There is no H8 instruction interpreter.</p></Section><Section title="Source baseline" info="Before port changes, the isolated source copy produced a byte-identical retail ROM with its original toolchain. The browser build changes the ABI and hardware interfaces."><div className="verification-line"><Check size={16}/><span>49,152 / 49,152 bytes identical</span></div><p className="hash">{proof?.expected_sha256||'f9e210a3b74afbbd12c5a66a51cc05cb9fbac986805ff0a3bfb4be6074d15607'}</p></Section><Section title="Verification"><div className="verification-line"><Check size={16}/><span>{verification?.passed||0} native checks passed</span></div><ul className="checks"><li>Eight EEPROM images boot and accept input.</li><li>EEPROM export preserves big-endian saves and checksums.</li><li>FFT samples produce steps and Watts.</li><li>Memory restore and forks replay deterministically.</li></ul><div className="metrics-row"><Metric label="Audio events" value={audio.current?.metrics().events??'Off'}/><Metric label="Audio latency" value={audio.current?Math.round(audio.current.metrics().latency)+' ms':'Off'}/><Metric label="Audio late events" value={audio.current?.metrics().late??'Off'}/><Metric label="Scene rate" value={metrics.fps+' fps'}/><Metric label="Longest frame" value={metrics.maxFrame.toFixed(1)+' ms'}/></div></Section><Section title="Scope"><p className="note">IR uses an offline timeout. Sensor forces and piezo acoustics are approximations. Physical behaviour and every firmware path have not been qualified against hardware.</p><div className="section-actions"><a href="/README.md" target="_blank" rel="noreferrer" className="text-link">Build and port notes</a><Button variant="outline" size="sm" onClick={()=>download(JSON.stringify({build,baseline:proof,verification,live:{stats:s,imports:frame?.imports}},null,2),'pokewalker-evidence.json','application/json')}><Download/>Evidence</Button></div></Section></TabsContent>
    </div></Tabs></aside>
  </main><footer className="app-footer"><span role="status">{notice}</span><span>{metrics.fps} fps · {frame?.speed||1}×<Info label="Timing">Scene frame rate and selected device speed. Browser background tabs pause the device to prevent missed timer intervals.</Info></span></footer>
 </div></TooltipProvider>
}
