import {useEffect,useRef,useState} from 'react'
import type {ReactNode} from 'react'
import {Info as InfoIcon} from 'lucide-react'
import {Tooltip,TooltipContent,TooltipTrigger} from '@/components/ui/tooltip'
import {Slider} from '@/components/ui/slider'
import {Input} from '@/components/ui/input'
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select'
export function Info({label,children}:{label:string,children:ReactNode}){return <Tooltip><TooltipTrigger asChild><button className="info" aria-label={'About '+label}><InfoIcon size={14}/></button></TooltipTrigger><TooltipContent className="max-w-72 text-xs leading-relaxed">{children}</TooltipContent></Tooltip>}
export function Choice({label,value,options,onChange}:{label:string,value:string,options:string[][],onChange:(s:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>}
export function Control({label,value,min,max,step=1,unit='',info,onChange}:{label:string,value:number,min:number,max:number,step?:number,unit?:string,info?:string,onChange:(n:number)=>void}){
 return <div className="control"><div className="control-top"><span>{label}{info&&<Info label={label}>{info}</Info>}</span><div className="control-number"><Input aria-label={label+' value'} type="number" min={min} max={max} step={step} value={Number(value.toFixed(3))} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(Math.max(min,Math.min(max,n)))}}/><span>{unit}</span></div></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(v[0])}/></div>
}
const light=[189,196,159],dark=[46,57,42]
export function LCD({pixels,className=''}:{pixels?:ArrayLike<number>,className?:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const ctx=ref.current?.getContext('2d');if(!ctx)return;const im=ctx.createImageData(96,64);for(let i=0;i<6144;i++){const v=(pixels?.[i]||0)/3;for(let c=0;c<3;c++)im.data[i*4+c]=light[c]+(dark[c]-light[c])*v;im.data[i*4+3]=255}ctx.putImageData(im,0,0)},[pixels]);return <canvas ref={ref} width={96} height={64} className={'lcd '+className} role="img" aria-label="Firmware LCD, 96 by 64 pixels"/>}
export function Plot({kind,data,index=0,other}:{kind:'wave'|'spectrum'|'memory'|'eeprom',data?:ArrayLike<number>,index?:number,other?:ArrayLike<number>}){
 const ref=useRef<HTMLCanvasElement>(null),[hover,setHover]=useState('');
 useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!c||!ctx)return;const w=c.width,h=c.height;ctx.clearRect(0,0,w,h);if(!data)return;
 if(kind==='wave'){ctx.strokeStyle='#e4e5e3';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,h*i/4);ctx.lineTo(w,h*i/4);ctx.stroke()}['#a65343','#467453','#53749d'].forEach((color,a)=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<64;i++){const v=data[a*64+(index+i)%64],x=i*w/63,y=h/2-v*h/256;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()})}
 if(kind==='spectrum'){const max=Math.max(700,...Array.from(data).slice(1)),bw=w/32;ctx.fillStyle='#ebf0e9';ctx.fillRect(bw*5,0,bw*10,h);for(let i=0;i<32;i++){ctx.fillStyle=i>=5&&i<=14?'#607b5d':'#b9bfbb';const bh=Math.max(2,data[i]/max*(h-8));ctx.fillRect(i*bw+2,h-bh,bw-4,bh)}ctx.strokeStyle='#9a8061';ctx.setLineDash([4,4]);const y=h-512/max*(h-8);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();ctx.setLineDash([])}
 if(kind==='memory'||kind==='eeprom'){const cols=kind==='memory'?64:32,rows=Math.ceil(data.length/cols),bw=w/cols,bh=h/rows;for(let i=0;i<data.length;i++){const v=data[i],write=other?.[i]||0;const alpha=kind==='memory'?.12+.88*v/255:Math.min(1,.15+Math.log2(v+write+1)/18);ctx.fillStyle=write?`rgba(161,90,55,${alpha})`:`rgba(66,98,78,${alpha})`;ctx.fillRect(i%cols*bw,Math.floor(i/cols)*bh,bw-1,bh-1)}}
 },[kind,data,index,other]);
 return <div className="plot"><canvas ref={ref} width={600} height={kind==='memory'?200:140} role="img" aria-label={{wave:'Accelerometer sample window',spectrum:'Firmware FFT spectrum',memory:'Workspace memory bytes',eeprom:'EEPROM access map'}[kind]} onMouseMove={e=>{if(!data||kind==='wave'||kind==='spectrum')return;const r=e.currentTarget.getBoundingClientRect(),cols=kind==='memory'?64:32,rows=Math.ceil(data.length/cols),i=Math.floor((e.clientY-r.top)/r.height*rows)*cols+Math.floor((e.clientX-r.left)/r.width*cols);if(i>=data.length)return;setHover(kind==='memory'?`+0x${i.toString(16).padStart(4,'0')} · ${data[i]}`:`0x${(i*128).toString(16).padStart(4,'0')} · ${data[i]} reads · ${other?.[i]||0} writes`)}}/>{hover&&<span className="plot-hover">{hover}</span>}</div>
}
export function Section({title,info,children}:{title:string,info?:string,children:ReactNode}){return <section className="panel-section"><h2>{title}{info&&<Info label={title}>{info}</Info>}</h2>{children}</section>}
export function Metric({label,value}:{label:string,value:ReactNode}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
export const viewName=(n:number)=>({0:'Home',1:'Menu',2:'Dowsing',3:'Poké Radar',4:'Battle',6:'Radar result',7:'Inventory',8:'Trainer card',9:'Settings',10:'Pokémon',11:'Items',12:'Social event',13:'Peer',14:'Connection result',15:'Walk start',16:'Walk end',17:'Event reward',22:'Diagnostics',23:'Motion test',24:'Motion result'}[n]||'View '+n)
export const time=(ms:number)=>`${Math.floor(ms/60000).toString().padStart(2,'0')}:${Math.floor(ms/1000%60).toString().padStart(2,'0')}.${Math.floor(ms%1000/10).toString().padStart(2,'0')}`
