import {mountModel} from './model.js';
const $=id=>document.getElementById(id),num=n=>Number(n).toLocaleString('en-US');
const viewNames={0:'Home',1:'Main menu',2:'Dowsing',3:'Poké Radar',4:'Battle',6:'Radar result',7:'Inventory choice',8:'Trainer card',9:'Settings',10:'Pokémon list',11:'Item list',12:'Social event',13:'Peer',14:'Connection result',15:'Walk start',16:'Walk end',17:'Event reward',22:'Diagnostics',23:'Motion test',24:'Motion result'};
const palette=[[181,187,151],[139,150,113],[83,104,71],[35,57,39]],colors=['#e69172','#b4d8a2','#a6b5df'];
const lcd=document.createElement('canvas');lcd.width=96;lcd.height=64;const lcdContext=lcd.getContext('2d');
const worker=new Worker('./runtime-worker.js',{type:'module'}),futuresWorker=new Worker('./futures-worker.js',{type:'module'});
let current,functions=[],build={},proof={},paused=false,manualPaused=false,keys=0,checkpoints=[],futureData=[],snapshotBusy=false,selectedFunction,model,modelError,hasSnapshot=false,lastSpectrumEpoch=-1,toastTimer,lastPulse=[],audioContext,oscillator,gain,audioEnabled=false;
window.pwLab={get state(){return current},get futures(){return futureData},get model(){return model},get modelError(){return modelError},worker,checkpoints};
function message(type,extra={}){worker.postMessage({type,...extra});}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
function renderLCD(canvas,pixels){const ctx=canvas.getContext('2d');canvas.width=96;canvas.height=64;const image=ctx.createImageData(96,64);for(let i=0;i<6144;i++){const c=palette[pixels[i]||0];image.data.set([...c,255],i*4);}ctx.putImageData(image,0,0);}
function canvasContext(id){const c=$(id);const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);return[c,ctx];}
function plotWave(samples,index){const[c,ctx]=canvasContext('wave');ctx.lineWidth=1;ctx.strokeStyle='#2a3d2c';for(let j=1;j<4;j++){ctx.beginPath();ctx.moveTo(0,j*c.height/4);ctx.lineTo(c.width,j*c.height/4);ctx.stroke();}for(let a=0;a<3;a++){ctx.beginPath();ctx.strokeStyle=colors[a];ctx.lineWidth=2;for(let i=0;i<64;i++){const v=samples[a*64+((index+i)%64)],x=i*c.width/63,y=c.height/2-v*c.height/256;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();}ctx.fillStyle='#bed6ab';ctx.fillRect(c.width-2,0,2,c.height);}
function plotSpectrum(bins){const[c,ctx]=canvasContext('spectrum');const max=Math.max(700,...bins.slice(1));const width=c.width/32;ctx.fillStyle='#a6cb8530';ctx.fillRect(width*5,0,width*10,c.height);for(let i=0;i<32;i++){const h=Math.min(1,bins[i]/max)*(c.height-7);ctx.fillStyle=i>=5&&i<=14?'#b8d99c':'#527953';ctx.fillRect(i*width+2,c.height-h,width-4,Math.max(h,2));}ctx.setLineDash([4,4]);ctx.strokeStyle='#c1aa7180';ctx.beginPath();const y=c.height-512/max*(c.height-7);ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke();}
function plotRam(bytes,task){const[c,ctx]=canvasContext('ram'),cols=128,rows=15,w=c.width/cols,h=c.height/rows;for(let i=0;i<bytes.length;i++){const region=i<64?'216,155,117':i<266?'169,204,145':'143,164,200';ctx.fillStyle=`rgba(${region},${.12+.88*bytes[i]/255})`;ctx.fillRect(i%cols*w,Math.floor(i/cols)*h,w-1,h-1);}ctx.strokeStyle=task===1?'#e7bd76':'#b4d89b';ctx.lineWidth=2;ctx.strokeRect(0,0,c.width,(task===1?2:3)*h);}
function plotHeat(read,write){const[c,ctx]=canvasContext('eeprom-heat'),cols=64,w=c.width/cols,h=c.height/8;for(let i=0;i<512;i++){const writes=write[i],reads=read[i];ctx.fillStyle=writes?`rgba(236,152,123,${Math.min(1,.3+Math.log2(writes+1)/22)})`:reads?`rgba(186,220,155,${Math.min(1,.16+Math.log2(reads+1)/24)})`:'#203426';ctx.fillRect(i%cols*w,Math.floor(i/cols)*h,w-2,h-2);}}
const featured=['MainTick','ViewUpdate','ViewRender','CaptureSample','MotionProcess','FftAccumulate'];
function initFunctions(){
 $('fn-total').textContent=functions.length+' FUNCTIONS';
 $('routine-list').replaceChildren(...featured.map(name=>{const f=functions.find(f=>f.name===name);const button=document.createElement('button');button.className='routine';button.dataset.fn=f?.id;button.innerHTML='<i></i><span></span><small>0</small>';button.querySelector('span').textContent=name;button.onclick=()=>openSource(f);return button;}));
 for(const f of functions){const opt=document.createElement('option');opt.value=f.id;opt.textContent=f.name+' · '+f.file; $('source-select').appendChild(opt);}
 $('source-select').onchange=()=>openSource(functions[Number($('source-select').value)]);
}
async function openSource(f=functions.find(f=>f.name==='MainTick')){
 if(!f)return;selectedFunction=f;$('source-title').textContent=f.name+'()';$('source-select').value=f.id;
 const text=await(await fetch('./source/'+f.file)).text(),lines=text.split('\n');let end=lines.length;
 const next=functions.filter(x=>x.file===f.file&&x.line>f.line).sort((a,b)=>a.line-b.line)[0];if(next)end=next.line-1;
 $('source-code').replaceChildren(...lines.slice(Math.max(0,f.line-3),end).map((line,i)=>{const n=f.line-2+i;const el=document.createElement('span');el.className='code-line'+(n===f.line?' current':'');const no=document.createElement('span');no.className='line-no';no.textContent=n;el.append(no,document.createTextNode(line));return el;}));
 $('source-code').scrollTop=0;if(!$('source-dialog').open)$('source-dialog').showModal();
}
function updateRoutineCounts(d){for(const row of document.querySelectorAll('.routine')){const i=+row.dataset.fn;row.querySelector('small').textContent=num(d.counts[i]);row.querySelector('i').style.width=Math.min(100,d.delta[i]*12)+'%';}if(selectedFunction)$('source-count').textContent=num(d.counts[selectedFunction.id])+' calls';}
function handleFrame(d){current=d;const s=d.stats;paused=d.paused;
 renderLCD(lcd,d.pixels);model?.updateScreen();model?.updatePose(d.pose);if(!model)renderLCD($('flat-lcd'),d.pixels);
 $('status').textContent=paused?'PAUSED':'NATIVE FIRMWARE RUNNING';$('live-dot').classList.toggle('paused',paused);$('pause').textContent=paused?'▷ Resume':'Ⅱ Pause';
 $('view-name').textContent=s[26]?'ASLEEP · HOLD CENTER':(viewNames[s[5]]||'View '+s[5]).toUpperCase();$('device-clock').textContent=new Date(s[19]*1000).toISOString().slice(11,19);
 $('steps').textContent=num(s[7]);$('watts').innerHTML=num(s[6])+'<span> W</span>';$('total').textContent=num(s[8]);
 ['ax','ay','az'].forEach((id,i)=>$(id).textContent=(d.accel[i]>=0?'+':'')+d.accel[i]);
 plotWave(d.samples,s[12]);plotRam(d.work,s[27]);plotHeat(d.heat,d.writeHeat);updateRoutineCounts(d);
 $('foreground').textContent=['MainTick','BeepTick','IR timeout'][s[27]];$('tick-cost').textContent=d.compute.toFixed(3)+' ms / tick';
 $('arena-caption').textContent=s[27]===1?'Sound owns bytes 64–255. These are the same bytes used by XYZ samples.':'Motion owns bytes 0–265. Scratch starts at +266; '+s[13]+' bytes are currently allocated.';
 $('window').innerHTML=s[12]+'<span> / 64</span>';$('window-bar').style.width=s[12]/64*100+'%';
 if(s[4]!==lastSpectrumEpoch){plotSpectrum(d.spectrum);lastSpectrumEpoch=s[4];}
 $('cadence-result').textContent=s[4]?(s[14]?(s[14]/2048).toFixed(2)+' Hz':'Rejected'):'Waiting';
 $('epoch-result').textContent=s[4]?num(s[4])+' epochs · '+s[21]+' steps in latest batch':'A fresh epoch takes 4 sec.';
 $('q9').innerHTML=s[20]+'<span> / 512</span>';$('fraction-bar').style.width=s[20]/512*100+'%';$('watt-progress').textContent=s[24]+' / 20 steps to the next Watt';
 $('reads').textContent=num(s[15]);$('writes').textContent=num(s[16]);
 if(audioEnabled&&oscillator){const hz=s[27]===1&&s[28]?32768/(s[28]+1):0;oscillator.frequency.setTargetAtTime(hz||100,audioContext.currentTime,.003);gain.gain.setTargetAtTime(hz&&s[33]?(s[33]===1?.016:.028):0,audioContext.currentTime,.004);}
}
function download(bytes,name,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function keyChange(value){keys=value;message('buttons',{value});for(const b of document.querySelectorAll('[data-key]'))b.classList.toggle('active',!!(value&+b.dataset.key));}
async function enableAudio(){if(audioEnabled)return;try{audioContext=new AudioContext();oscillator=audioContext.createOscillator();gain=audioContext.createGain();oscillator.type='square';gain.gain.value=0;oscillator.connect(gain).connect(audioContext.destination);oscillator.start();await audioContext.resume();audioEnabled=true;}catch{}}
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);keyChange(keys|+b.dataset.key);enableAudio();};b.onpointerup=b.onpointercancel=()=>keyChange(keys&~+b.dataset.key);}
const keyMap={ArrowLeft:4,ArrowRight:8,' ':2,Enter:2};
window.addEventListener('keydown',ev=>{if(document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes(ev.target.tagName))return;if(keyMap[ev.key]){ev.preventDefault();keyChange(keys|keyMap[ev.key]);enableAudio();}});
window.addEventListener('keyup',ev=>{if(keyMap[ev.key]){ev.preventDefault();keyChange(keys&~keyMap[ev.key]);}});
window.addEventListener('blur',()=>keyChange(0));
$('pause').onclick=()=>{manualPaused=!paused;message('pause',{value:manualPaused});};$('step').onclick=()=>{manualPaused=true;message('step');};
document.addEventListener('visibilitychange',()=>message('pause',{value:document.hidden||manualPaused}));
function setMode(mode){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));message('physics',{value:{mode}});}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>setMode(b.dataset.mode);
$('power').oninput=()=>{$('power-value').textContent=$('power').value+'%';message('physics',{value:{fan:$('power').value/100,mode:'fan'}});document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='fan'));};
$('cadence').oninput=()=>{$('cadence-value').textContent=($('cadence').value/100).toFixed(2)+' Hz';message('physics',{value:{cadence:$('cadence').value/100,mode:'walk'}});document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='walk'));};
$('fixture').onchange=async()=>{manualPaused=false;$('fault').hidden=true;lastSpectrumEpoch=-1;const value=$('fixture').value;if(value==='blank'){message('blank');return;}const bytes=await(await fetch('./fixtures/'+encodeURIComponent(value))).arrayBuffer();message('load',{bytes,label:$('fixture').selectedOptions[0].textContent});};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;if(file.size!==65536){toast('Choose a 65,536-byte EEPROM image.');$('file').value='';return;}const bytes=await file.arrayBuffer();manualPaused=false;$('fault').hidden=true;message('load',{bytes,label:file.name});toast('Loading '+file.name);$('file').value='';};
$('export').onclick=()=>message('save');$('reset').onclick=()=>{manualPaused=false;$('fault').hidden=true;message('reset');};$('recover').onclick=()=>$('fixture').onchange();
$('checkpoint').onclick=()=>message('checkpoint');
function addCheckpoint(d){if(checkpoints.length===8){checkpoints.shift();$('checkpoints').firstElementChild?.remove();}checkpoints.push(d);if($('checkpoints').querySelector('.empty-note'))$('checkpoints').replaceChildren();const button=document.createElement('button');button.className='checkpoint';const canvas=document.createElement('canvas');renderLCD(canvas,d.pixels);const span=document.createElement('span');span.textContent=(viewNames[d.stats[5]]||'View')+'\n'+num(d.stats[7])+' steps · restore';button.append(canvas,span);button.onclick=()=>{message('restore',{state:d.state});manualPaused=true;toast('State restored and paused. Resume to take another path.');};$('checkpoints').appendChild(button);toast('Exact running state captured.');}
const branchTitles=['No input','Left','Center','Right','Start walking','Stillness'];
function futurePlaceholders(){for(let i=0;i<6;i++){const card=document.createElement('div');card.className='future';card.innerHTML=`<div class="future-top">${branchTitles[i]}<span>0${i+1}</span></div><div class="future-placeholder">AWAITING FORK</div><div class="future-outcome"><span>+— steps</span><span>— W</span></div><div class="future-state">Same starting state</div>`;$('futures').appendChild(card);}}
$('fork').onclick=()=>{if(snapshotBusy)return;snapshotBusy=true;$('fork').disabled=true;$('fork').textContent='Running six futures…';$('future-status').textContent='Cloning native memory and executing six independent branches…';message('snapshot');};
function renderFutures(){const index=+$('future-time').value;$('future-time-value').textContent='+'+(index+1)+' sec';$('futures').replaceChildren();futureData.forEach((b,i)=>{const card=document.createElement('div');card.className='future';const title=document.createElement('div');title.className='future-top';title.append(document.createTextNode(b.name));const n=document.createElement('span');n.textContent='0'+(i+1);title.append(n);const c=document.createElement('canvas');renderLCD(c,b.frames[index]);const outcome=document.createElement('div');outcome.className='future-outcome';outcome.innerHTML='<span>+'+b.steps[index]+' steps</span><span>'+num(b.stats[6])+' W at 12s</span>';const state=document.createElement('div');state.className='future-state';state.textContent=b.states.map(v=>viewNames[v]||v).join(' → ');const spark=document.createElement('canvas');spark.width=160;spark.height=24;spark.className='future-spark';const ctx=spark.getContext('2d');ctx.strokeStyle='#b7d49c';ctx.lineWidth=2;ctx.beginPath();const max=Math.max(1,...b.steps);b.steps.forEach((s,j)=>{const x=j*160/11,y=22-s/max*20;j?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();card.append(title,c,outcome,state,spark);$('futures').appendChild(card);});}
$('future-time').oninput=renderFutures;
futuresWorker.onmessage=({data:d})=>{snapshotBusy=false;$('fork').disabled=false;$('fork').innerHTML='Explore this moment <span>↗</span>';if(d.type==='error'){toast('Future simulation stopped: '+d.message);$('future-status').textContent='One branch encountered a firmware fault.';return;}futureData=d.branches;renderFutures();$('future-status').textContent='Six futures from the same memory snapshot. The live device was untouched.';$('future-speed').textContent='72 device seconds / '+d.elapsed.toFixed(0)+' ms · '+Math.round(72000/d.elapsed)+'× throughput';hasSnapshot=true;};
worker.onmessage=({data:d})=>{if(d.type==='frame')handleFrame(d);else if(d.type==='save'){download(d.bytes,'pokewalker-'+new Date().toISOString().replaceAll(':','-')+'.bin');toast('Live save committed to EEPROM and exported (64 KiB).');}else if(d.type==='checkpoint')addCheckpoint(d);else if(d.type==='snapshot')futuresWorker.postMessage(d,[d.memory]);else if(d.type==='loaded'){setMode('still');toast(d.label+' loaded');lastSpectrumEpoch=-1;}else if(d.type==='error'){console.error(d.message);$('fault').hidden=false;$('fault-message').textContent=d.message;$('status').textContent='FIRMWARE PAUSED';}};
worker.onerror=ev=>{console.error(ev);$('fault').hidden=false;$('fault-message').textContent='The runtime worker stopped. Reload a fixture to restart.';};
$('open-source').onclick=()=>openSource();for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('about').onclick=$('proof-open').onclick=()=>$('about-dialog').showModal();
$('download-report').onclick=()=>download(JSON.stringify({build,baseline:proof,live:{imports:current?.imports,stats:current?.stats},futureTimings:futureData.map(b=>({branch:b.name,milliseconds:b.elapsed}))},null,2),'pokewalker-build-evidence.json','application/json');
try{model=mountModel($('model'),lcd,drag=>{message('physics',{value:{drag}});},key=>{keyChange(key);enableAudio();});}catch(error){modelError=error.message;$('model-fallback').hidden=false;console.warn('3D fallback:',error);}
futurePlaceholders();
Promise.all([fetch('./generated/functions.json').then(r=>r.json()),fetch('./generated/build.json').then(r=>r.json()),fetch('./generated/baseline.json').then(r=>r.json())]).then(([f,b,p])=>{functions=f;build=b;proof=p;initFunctions();$('unit-count').textContent=b.sources.length+' C translation units';$('wasm-size').textContent=(b.wasmBytes/1024).toFixed(0)+' KiB · 0 JS imports';worker.postMessage({type:'init'});}).catch(error=>{$('status').textContent='LOAD FAILED';$('fault').hidden=false;$('fault-message').textContent=error.message;});
